Repository skycoin/libskycoin, pull requests merged in 2019-07, with the labels that each got.

#91 Fixes #75 Correcting deploy in Circle CI
  .circleci/config.yml
  ci-scripts/deploy-arm.sh
  docker/images/deploy-arm/Dockerfile
Labels: ci, stdev, wip

#92 Merge V0.25dev into master , attempt 2
  .circleci/config.yml
  ci-scripts/deploy-arm.sh
  docker/images/deploy-arm/Dockerfile
Labels: arch-arm64, arch-armel, arch-armhf, ci, stdev, wip

#93 Fixes #75 Correcting the deploy ruling in Circle CI
  .circleci/config.yml
Labels: ci, stdev, wip

#94 Merge v0.25dev into master attempt 3
  .circleci/config.yml
Labels: ci, stdev, wip

#82 Fixes #79 Including certain missing skycoin cipher lib test vectors
  include/json.h
  lib/cgo/cipher.base58.base58.go
  lib/cgo/cipher.secp256k1-go.secp256k1.go
  lib/cgo/tests/check_cipher.address.c
  lib/cgo/tests/check_cipher.crypto.c
  lib/cgo/tests/check_cipher.hash.c
  lib/cgo/tests/check_cipher.secp256k1.c
  lib/cgo/tests/check_coin.block.c
  lib/cgo/tests/check_coin.outputs.c
  lib/cgo/tests/check_coin.transactions.c
  lib/cgo/tests/test_main.c
  lib/cgo/tests/test_main.h
Labels: ci, stdev, swig, wip

#96 Fixes #95 Fixes #75 Repairing libcurl compilation for 0.26.0 ARM
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  README.md
  ci-scripts/deploy-arm.sh
  ci-scripts/docker_install_debian.sh
  ci-scripts/docker_install_ubuntu.sh
  docker/images/deploy-arm/Dockerfile
  docker/images/test-arm/Dockerfile
  lib/cgo/tests/testutils/libsky_assert.c
  lib/curl/CMakeLists.txt
  lib/curl/install_lib_curl.sh
  lib/swig/dynamic/mem.i
  lib/swig/dynamic/typemaps.i
Labels: ci, stdev, wip

#99 Fixes #98 Missing export functions
  CHANGELOG.md
  lib/cgo/coin.block.go
  lib/cgo/coin.transactions.go
  lib/cgo/tests/check_cipher.crypto.c
  lib/cgo/tests/check_cipher.testsuite.c
  lib/cgo/tests/check_coin.block.c
  lib/cgo/tests/check_coin.transactions.c
  lib/cgo/tests/cipher.testsuite.c
Labels: stdev, swig, wip

#100 Fixed delete automated release 0.26.0
  docker/images/deploy-arm/Dockerfile
Labels: arch-arm64, arch-armel, arch-armhf, ci, stdev, wip

#101 Fixed missing package in deploy 0.26.0
  ci-scripts/docker_install_debian.sh
Labels: ci, stdev, wip
