Repository skycoin/libskycoin, pull requests merged in 2019-05, with the labels that each got.

#24 Fixes #7 Refactoring the criterion tests to libcheck
  .github/pull_request_template.md
  .gitignore
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  ci-scripts/install-travis-gcc.sh
  ci-scripts/integration-test-auth.sh
  ci-scripts/integration-test-disable-gui.sh
  ci-scripts/integration-test-disable-wallet-api.sh
  ci-scripts/integration-test-enable-seed-api.sh
  ci-scripts/integration-test-live.sh
  ci-scripts/integration-test-stable.sh
  ci-scripts/run-live-integration-test-node-cover.sh
  ci-scripts/run-live-integration-test-node.sh
  include/cipher.testsuite.testsuite.go.h
  include/skyassert.h
  include/skycriterion.h
  include/skyerrors.h
  include/skytest.h
  include/skytxn.h
  include/skytypes.h
  include/util.http.json.go.h
  lib/cgo/cipher.address.go
  lib/cgo/cipher.base58.base58.go
  lib/cgo/cli.cli.go
  lib/cgo/libsky_mem.go
  lib/cgo/params.droplet.go
  lib/cgo/tests/check_cipher.address.c
  lib/cgo/tests/check_cipher.bitcoin.c
  lib/cgo/tests/check_cipher.crypto.c
  lib/cgo/tests/check_cipher.encrypt.scrypt_chacha20poly1305.c
  lib/cgo/tests/check_cipher.hash.c
  lib/cgo/tests/check_cipher.testsuite.c
  lib/cgo/tests/check_coin.block.c
  lib/cgo/tests/check_coin.coin.c
  lib/cgo/tests/check_coin.math.c
  lib/cgo/tests/check_coin.outputs.c
  lib/cgo/tests/check_coin.transactions.c
  lib/cgo/tests/check_params.distribution.c
  lib/cgo/tests/check_util.droplet.c
  lib/cgo/tests/check_util.fee.c
  lib/cgo/tests/cipher.testsuite.c
  lib/cgo/tests/interface/xunit_interface.h
  lib/cgo/tests/shared_tests.c
  lib/cgo/tests/shared_tests.h
  lib/cgo/tests/test_main.c
  lib/cgo/tests/test_main.h
  lib/cgo/tests/testutils/criteiun_wrapper_calls.c
  lib/cgo/tests/testutils/criteiun_wrapper_calls.h
  lib/cgo/tests/testutils/json_util.c
  lib/cgo/tests/testutils/libsky_assert.c
  lib/cgo/tests/testutils/libsky_criterion.c
  lib/cgo/tests/testutils/libsky_string.c
  lib/cgo/tests/testutils/libsky_testutil.c
  lib/cgo/tests/testutils/transutils.c
Labels: ci, stdev, swig, wip

#29 Fixes #11 Device build matrix
  .travis.yml
  ci-scripts/docker_install_alpine.sh
  ci-scripts/docker_install_debian.sh
  ci-scripts/docker_install_fedora.sh
  ci-scripts/docker_install_ubuntu.sh
  docker/images/test-arm/Dockerfile
  lib/cgo/tests/check_coin.block.c
  lib/cgo/tests/check_coin.outputs.c
  lib/cgo/tests/testutils/libsky_assert.c
Labels: arch-amd64, arch-arm64, arch-armel, arch-armhf, arch-i386, ci, stdev, wip

#39 Fixes #37 Silencing library compilation
  include/skyassert.h
  lib/cgo/tests/testutils/criteiun_wrapper_calls.c
  lib/cgo/tests/testutils/criteiun_wrapper_calls.h
Labels: stdev, swig, wip

#35 Fixes #11 Device build matrix amd64
  .travis.yml
Labels: ci, stdev, swig, wip

#45 Reduce the travis build matrix
  .travis.yml
Labels: stdev, wip

#46 fixes #44 - Travis ARM builds
  .travis.yml
Labels: ci, stdev, wip

#48 Fixes #47 Support Circle CI
  .circleci/config.yml
  .golangci.libcgo.yml
  .travis.yml
  Makefile
  ci-scripts/install-travis-gcc.sh
  docker/images/test-arm/Dockerfile
  lib/cgo/tests/testutils/libsky_assert.c
Labels: arch-arm64, arch-armhf, stdev, wip

#43 Fixes #19 make docs
  Makefile
  README.md
  docs/curl/.openapi-generator-ignore
  docs/curl/.openapi-generator/VERSION
  docs/curl/index.html
  docs/libc/API.md
  lib/cgo/README.md
Labels: docs, stdev, wip

#52 refs #32 - Filter libskycoin events in CHANGELOG
  CHANGELOG.md
Labels: docs, stdev, wip

#31 Fixes #18 Document release procedure
  .travis.yml
  Makefile
  README.md
  ci-scripts/build.sh
  ci-scripts/install-golangci-lint.sh
  docker/images/test-arm/Dockerfile
Labels: docs, stdev, wip

#54 fixes #18 - Fix Travis deploy prior to 0.25.1
  .travis.yml
Labels: ci, stdev, wip

#53 Fixes #51 Skyapi make targets
  .travis.yml
  .travis/install_lib_curl.sh
  Makefile
  README.md
  lib/curl/CMakeLists.txt
  lib/curl/install_lib_curl.sh
Labels: ci, openapi, stdev

#55 Fixes #47 Automate deploy in Circle CI
  .circleci/config.yml
  docker/images/circle/Dockerfile
  lib/cgo/tests/check_coin.transactions.c
Labels: arch-arm64, arch-armel, arch-armhf, ci, stdev, wip

#60 refs #30 - Prepare release 0.25.1
  CHANGELOG.md
  README.md
Labels: ci, docs, stdev, wip

#63 Fixes #30 Move docker deploy ARM
  .circleci/config.yml
  docker/images/deploy-arm/Dockerfile
Labels: docker, stdev, wip
